### ISSUE TITLE
Galerija

### ISSUE THREAD

**Issue by Siclol** [Jaspero/autism-center-osijek#15]
- [x] Pull real data from database
- [x] Show a few (your call) galleries initially, and add a load more button
- [x] Create a "single gallery" component

**Comment by flauc** [comment]
@Siclol 

Style of load more row

**Comment by Siclol** [comment]
- [ ] Style gallery carousel

**Comment by Siclol** [comment]
@flauc html should have overflow: hidden when gallery is opened
