### ISSUE TITLE
Program Segment Images

### ISSUE THREAD

**Issue by flauc** [Jaspero/autism-center-osijek#19]

**Comment by markovranjesevic** [comment]
Napisat cu ti svaki segment, i ispod stavit odgovarajuću sliku.

**Vrtićki program
![1](https://user-images.githubusercontent.com/53516961/66713339-ee9c7e00-eda9-11e9-8e04-4c95b2860be2.JPG)

**Posebni program uz individualizirane postupke
![40](https://user-images.githubusercontent.com/53516961/66713353-1c81c280-edaa-11e9-9e7a-406effdee575.JPG)

**Posebni program za stjecanje kompetencija u aktivnostima svakodnevnog života i rada uz individualizirane postupke
![8](https://user-images.githubusercontent.com/53516961/66713358-31f6ec80-edaa-11e9-8cd0-fce9896bb522.JPG)

**Produženi stručni postupak
![7](https://user-images.githubusercontent.com/53516961/66713362-46d38000-edaa-11e9-9097-7906ecfd574e.JPG)

**Logopedska terapija
![11](https://user-images.githubusercontent.com/53516961/66713368-55ba3280-edaa-11e9-83b7-57ba5a95b25b.JPG)

**Muzikoterapija
![10](https://user-images.githubusercontent.com/53516961/66713379-6f5b7a00-edaa-11e9-85f1-fedc8708b138.JPG)

**Senzorna integracija
![38](https://user-images.githubusercontent.com/53516961/66713383-839f7700-edaa-11e9-8697-52fb4a69addf.JPG)

**Vrtlarstvo
![53155163_1301904539952466_8322585178610335744_o](https://user-images.githubusercontent.com/53516961/66713387-9e71eb80-edaa-11e9-9179-7eaad1d81211.png)

**Domaćinstvo
![15](https://user-images.githubusercontent.com/53516961/66713390-ac277100-edaa-11e9-90bf-f782ac7bb639.JPG)

**Mali englezi
![viber_image_2019-07-18_15-09-29](https://user-images.githubusercontent.com/53516961/66713419-fc063800-edaa-11e9-80df-947de5a0793d.png)

**Radno kreativne radionice
![39](https://user-images.githubusercontent.com/53516961/66713426-1cce8d80-edab-11e9-95e9-07e55bc024dd.JPG)

**Comment by markovranjesevic** [comment]
Kad vidis ovo, javi mi samo hoce li "Mali englezi" i "Vrtlarstvo" biti premale datoteke? (te dvije slike su s weba, ostalo imamo profi njihove sve)
