### ISSUE TITLE
Project Short Descriptions

### ISSUE THREAD

**Issue by flauc** [Jaspero/autism-center-osijek#21]

**Comment by markovranjesevic** [comment]
Project Short Descriptions

-Asistent u nastavi

*Pomoćnike u vrtiću osigurava Grad Osijek na temelju zahtjeva koji zajedno s potrebnom 
dokumentacijom podnosi Centar. 


-OSIgurajmo im JEdnaKost 4

*Projekt OSIgurajmo im JEdnaKost 4 sufinanciran je sredstvima Europske unije iz Europskog 
socijalnog fonda, a vodi ga Grad Osijek zajedno s partnerima.Projektom je omogućena stručna 
podrška pomoćnika u nastavi učenicima s teškoćama u razvoju, kojima su najpotrebniji. 


-Primjena tehnologije 21. stoljeća za 
promociju komunikacije, obrazovanja i 
socijalnog uključivanja djece rane dobi s 
teškoćama u razvoju

* Centar za autizam uključio se u projekt Primjena tehnologije 21. stoljeća za promociju komunikacije, 
obrazovanja i socijalnog uključivanja djece rane dobi s teškoćama u razvoju. 
Projekt se provodi u suradnji Unicefa, Edukacijsko rehabilitacijskog fakulteta i Fakulteta elektrotehnike i računarstva.


-Volontiranje

*Volonterstvo (volontiranje, volonterski/dobrovoljni rad) u najširem značenju podrazumijeva rad 
pojedinca na dobrobit drugih pri čemu je njegovo djelovanje slobodno odabrano, neprofitno i bez 
financijske dobiti.
