### ISSUE TITLE
Meta for pages

### ISSUE THREAD

**Issue by flauc** [Jaspero/autism-center-osijek#23]
We need to add the proper titles, descriptions and keywords to all of the pages

**Comment by markovranjesevic** [comment]
Meta page descriptions:

O nama page - Kako smo nastali, koja nam je misija i vizija te tko su naši djelatnici

Programi page - Saznajte više o osnovnim programima, terapijskim postupcima i izvannastavnim aktivnostima koje se provode u Centru

Projekti page - Aktualni projekti i suradnja

Novosti page - Provjerite najnovije obavijesti i pratite novosti vezane uz rad Centra

Galerija page - Istražite fotografije Centra i pogledajte galeriju raznih događanja u sklopu rada Centra

Kontakt page - Saznajte kontakt informacije, provjerite gdje se nalazimo i postavite upit

**Comment by flauc** [comment]
@markovranjesevic 
Fali nam samo za home page description

**Comment by markovranjesevic** [comment]
Centar za autizam Osijek, najmoderniji regionalni centar za djecu s poremećajem iz spektra autizma.Saznajte o programima, terapijskim postupcima i aktivnostima.
