### ISSUE TITLE
Content: Projekti

### ISSUE THREAD

**Issue by Siclol** [Jaspero/autism-center-osijek#3]

**Comment by markovranjesevic** [comment]
[PROJEKT Asistent u nastavi.docx](https://github.com/Jaspero/autism-center-osijek/files/3451141/PROJEKT.Asistent.u.nastavi.docx)
[PROJEKT OSIgurajmo im JEdnaKost 4.docx](https://github.com/Jaspero/autism-center-osijek/files/3451142/PROJEKT.OSIgurajmo.im.JEdnaKost.4.docx)
[volontiranje.docx](https://github.com/Jaspero/autism-center-osijek/files/3451143/volontiranje.docx)
