### ISSUE TITLE
New page: Dokumenti

### ISSUE THREAD

**Issue by Siclol** [Jaspero/autism-center-osijek#34]
- [ ] Create a collection on CMS in which users can add new documents (pdf and docx). Each document has [name] and [file upload].
- [ ] Create a new page on website. This page will display all the documents from the previously mentioned collection, with each document being clickable to download the file.

Flip the task to me when you're done so I can style it.

**Comment by flauc** [comment]
@svendjanis I've added the FileComponent to JMS
