### ISSUE TITLE
Content: Footer

### ISSUE THREAD

**Issue by Siclol** [Jaspero/autism-center-osijek#8]

**Comment by markovranjesevic** [comment]
[God plan i program CENTRA.pdf](https://github.com/Jaspero/autism-center-osijek/files/3451160/God.plan.i.program.CENTRA.pdf)
[KURIKULUM CENTRA.docx](https://github.com/Jaspero/autism-center-osijek/files/3451161/KURIKULUM.CENTRA.docx)

**Comment by markovranjesevic** [comment]
[Pravilnik o nacinu i postupku zaposljavanja.docx.docx](https://github.com/Jaspero/autism-center-osijek/files/3451173/Pravilnik.o.nacinu.i.postupku.zaposljavanja.docx.docx)
[PRAVILNIK o sistematizaciji radnih mjesta.docx](https://github.com/Jaspero/autism-center-osijek/files/3451176/PRAVILNIK.o.sistematizaciji.radnih.mjesta.docx)
[STAtut  CZA.docx](https://github.com/Jaspero/autism-center-osijek/files/3451178/STAtut.CZA.docx)
[Zahtjev_1_za_pristup_informacijama_Obrazac_br.1.docx](https://github.com/Jaspero/autism-center-osijek/files/3451179/Zahtjev_1_za_pristup_informacijama_Obrazac_br.1.docx)
[Zahtjev_2 za_dopunu_ili_ispravak_informacije_Obrazac_br.2).docx](https://github.com/Jaspero/autism-center-osijek/files/3451180/Zahtjev_2.za_dopunu_ili_ispravak_informacije_Obrazac_br.2.docx)
[Zahtjev_3 za_ponovnu_uporabu_informacija_Obrazac_br.3.docx](https://github.com/Jaspero/autism-center-osijek/files/3451183/Zahtjev_3.za_ponovnu_uporabu_informacija_Obrazac_br.3.docx)
